#!/bin/bash

chmod +x /usr/local/bin/*

# Create virtual environment for Flask app
python -m venv /usr/local/infopanel/flask/venv

# Set console login
sudo systemctl --quiet set-default isolate multi-user

# Set autologin for pi
mkdir -p /etc/systemd/system/getty@tty1.service.d
cat > /etc/systemd/system/getty@tty1.service.d/autologin.conf << EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin pi --noclear %I xterm-256color
EOF

# Notify that reboot is required
echo "Please reboot after installation"
